### ISSUE TITLE
The text editor appears behind the sidebar

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/files_texteditor#106]
Due to the layout changes in server for Nextcloud 14 the text editor appears behind the sidebar.

The sidebar is now a sibling of `#app-content` instead of a child. As the sidebar has a higher _z-index_ ([1500](https://github.com/nextcloud/server/blob/755f13ee9f8543654a7e2a65b0d7f38378406c4a/core/css/apps.scss#L647)) than `#app-content` ([1000](https://github.com/nextcloud/server/blob/755f13ee9f8543654a7e2a65b0d7f38378406c4a/core/css/apps.scss#L598)) every child of `#app-content`, no matter its _z-index_, will appear behind the sidebar.

When the children are kept inside the bounds of the `#app-content` that does not matter, but when it overflows them (like the text editor, which is shown in a sort of modal dialog) the result is buggy:

![sidebar-overlaps-text-editor](https://user-images.githubusercontent.com/26858233/43714610-d762c04a-997d-11e8-9203-e7c0eb16cad8.png)

In order to keep the same behaviour for the text editor:
- In the server _z-index_ of the sidebar is made lower than the _z-index_ of the `#app-content` (if it were equal the issue would exist anyway due to the sidebar appearing in the DOM after the app content).
- The text editor is appended to the content instead of the app content, so it is not bound to its _z-index_.
- More options I have not thought of :-)

Another approach, of course, would be to change the behaviour of the text editor to not use a modal dialog anymore, but that would need a lot more work to decide the new behaviour and implement it.

@nextcloud/designers

**Comment by rullzer** [comment]
I believe @skjnldsv fixed most of the isses already.

**Comment by schiessle** [comment]
Without the sidebar it looks good. But with the sidebar it is still broken. Tested it today with current master

**Comment by juliushaertl** [comment]
@skjnldsv It seems that there is an issue with the z-index of 1000 of the app-content. It seems that this causes the browser to ignore the higher z-index of the texteditor container that should be above the sidebar. Do you remember the reason for this setting it to 1000? 

https://github.com/nextcloud/server/commit/248b786bd0e9fdb01af8aa43af5f763d029d5c2e#diff-bf0066932907b556b49ffe55b209a501L598

**Comment by skjnldsv** [comment]
@juliushaertl It was just to set it under some other content I guess --"
Liek I said, we really need to define a list of those zindexes :p
