### ISSUE TITLE
Nextcloud 15, code folding not working (TypeError: ace.require(...) is undefined)

### ISSUE THREAD

**Issue by rexxmagnus** [nextcloud/files_texteditor#126]
### Steps to reproduce
1. Upgrade to nextcloud 15
2. Open an xml file with outline elements

### Expected behaviour
Code folding arrows should appear next to <outline> elements in xml file

### Actual behaviour
No code folding marks appear, javascript throws an error "TypeError: ace.require(...) is undefined" in index.php/js/files_texteditor/merged.js:547:12

**Comment by meliurwen** [comment]
_Maybe_ I'm wrong, but I do not recall this feature.
Anyway, I have the same error on **Nextcloud 15.0.4** with **text editor 2.7.0** and it seems linked to the **syntax hghlighting** issue (#122).
