### ISSUE TITLE
Context menu entry not translated

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files_texteditor#179]
![menu](https://user-images.githubusercontent.com/5836855/64095010-e3dbdb80-cd5d-11e9-9cd3-8bda737ac7a5.png)

Context menu entry is not translated.

**Comment by tobiasKaminsky** [comment]
@juliushaertl @skjnldsv maybe?

**Comment by skjnldsv** [comment]
Yep https://github.com/nextcloud/files_texteditor/blob/c25308fa2656d68154d75c7ae1017864c2f236a3/js/editor.js#L248

**Comment by tobiasKaminsky** [comment]
@juliushaertl can yo do a stable release? As this is is for a customer it would be good to have this soon in.
(well, maybe we need to wait one week for translation…)

**Comment by juliushaertl** [comment]
For 16 files_texteditor was bundled with the server, so we need to wait for the next maintenance release.

**Comment by juliushaertl** [comment]
Not sure how we handle this app for 17+ since we switched to https://github.com/nextcloud/text for our default text editor. Should we still push a release to the app store as long as the app keeps working? @rullzer

**Comment by skjnldsv** [comment]
I'd say, we should maybe deprecate it and stop for nc20?
