### ISSUE TITLE
Server version 19 or higher is required

### ISSUE THREAD

**Issue by syltao** [nextcloud/files_texteditor#229]
### Steps to reproduce
1. Copying  files_texteditor folder in nextcloud/app/
2. Open Nextcloud as admin
3. Access "Applications"

### Expected behaviour
Plain text editor appear in Un-active application : OK
Want to activate but:

### Actual behaviour
Ask for Server version 19
"Server version 19 or higher is required"

### Server configuration
**Nextcloud version:**
Stable : 18.0.3
(19 is beta)

**Where did you install Nextcloud from:**
Online update via Nextcloud

**Comment by juliushaertl** [comment]
Fixed with the app store release
