### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by SuperSayu** [nextcloud/files_texteditor#41]
Typing normally into the text editor can cause the error, "Cannot save file as it has been modified since opening".  This issue is intermittent, and the message can pop up before clearing.  However, in several cases so far, the editor has become locked in a position where it refuses to save, either by the autosave timer or by hitting Ctrl-S.  Network issues are suspected but cannot be definitively fingered.

Files are not shared and have only a single editor.  Running version 2.4.1 on Nextcloud 12, but issue existed under NC11.  Operating on a hosted virtual server through DigitalOcean.

<details><summary>Server configuration</summary>

**Operating system**: Linux 3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64

**Web server:** Apache/2.4.7 (Ubuntu) (apache2handler)

**Database:** mysql 5.5.55

**PHP version:** 7.0.19-1+deb.sury.org~trusty+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade

**Where did you install Nextcloud from:** Automatic updater whenever possible
</details>

<details>
	<summary>App list</summary>

```
Enabled:
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - dav: 1.3.0
 - drawio: 0.8.8
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_facebook: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - activity
 - comments
 - documents
 - encryption
 - files_external
 - files_versions
```

</details>
<details><summary>Nextcloud configuration</summary>

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocf6sclickns",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "fcg",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/",
        "has_internet_connection": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "theme": ""
    }
}
</details>

<details><summary>Client configuration</summary>

**Browser:** Chrome

**Operating system:** Windows 10</details>

Nextcloud log contains *many* copies of the following (with different request IDs):
{"reqId":"4bBBcQoU0sqFFWFBNont", "level":3, "time":"2017-06-08T17:41:12+00:00", "remoteAddr":"---", "user":"---", "app":"files_texteditor", "method":"PUT", "url":"\/apps\/files_texteditor\/ajax\/savefile", "message":"File: \/testfile.txt modified since opening.", "userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

**Comment by SuperSayu** [comment]
Chrome JS console:

Failed to load resource: the server responded with a status of 400 (Bad request) https://[server]/apps/files_texteditor/ajax/savefile

PUT https://[server]/apps/files_texteditor/ajax/savefile 400 (Bad request)
send	@	core.js:4
ajax	@	core.js:4
saveFile	@	merged.js?v=79ca4c103acf2d5693fde46ac20c0cc3-3:584
_onSaveTrigger	@	merged.js?v=79ca4c103acf2d5693fde46ac20c0cc3-3:101

**Comment by mind22** [comment]
I have the same problem. Is there any new approach?

 I assume it is because of the file locking by apcu/redis. It seems that the editor is unable to unlock the current file before saving. The first two or three times the editor has no problem with saving in between after writing some lines, but after this it is not able to unlock it anymore.

**Comment by SuperSayu** [comment]
I notice that the save timer does not work correctly.  It is supposed to only save 3 seconds after you stop typing, but it never clears the timer.  If you watch the save message after typing, it will flicker between "Saving" and "Saved".  I am pretty sure that this is why it is occasionally having this problem: it gets a save request for every character sent, and the pile-up causes messages to arrive out of order, screwing everything up afterwards.

I believe https://github.com/nextcloud/files_texteditor/blob/master/js/editor.js#L638 is supposed to use OCA.files_texteditor instead of "this"
