### ISSUE TITLE
Editing an existing txt file on ios reset contents without the possibility to recovery

### ISSUE THREAD

**Issue by gabriel-joy** [nextcloud/files_texteditor#485]
### Steps to reproduce
1. create a txt file on pc by using web interface or notepad and add contents
2. edit the file on your ios mobile

### Expected behaviour
a new version to be saved

### Actual behaviour
file contents are erased, no previous version available

### Server configuration
Nextcloud 21.05

**Comment by 01tot10** [comment]
There's a related issue also on Android (#104), where editing a text files can easily result in all text wiped out, without possibility to recover. I don't know how related they are technically speaking though, symptoms are identical though.

**Comment by gabriel-joy** [comment]
It doesn't reproduce anymore.
