### ISSUE TITLE
Please add Compatibility for NC24

### ISSUE THREAD

**Issue by jet438** [nextcloud/files_texteditor#572]
Please add compatibility for NC24
```

**Comment by elpraga** [comment]
I've upgraded to NC24, enabled the Plain Text Editor app as an untested app, and it works as expected.

**Comment by jet438** [comment]
Hmmm?...I'm not seeing it available

**Comment by jet438** [comment]
I'm still showing it as incompatible. I even tried disable/remove/install.

**Comment by kruthoff** [comment]
I prefer this app to edit markup files for the pico app. The other text app modifies the markup files in a way that they don't run on pico anymore.

**Comment by the-wolfman** [comment]
> I prefer this app to edit markup files for the pico app. The other text app modifies the markup files in a way that they don't run on pico anymore.

Fully aggre with kruthoff on this. Basically I am using  the texteditor for almost anything that needs straight forward markdown source editing.

**Comment by ruedigerkupper** [comment]
If it works on NC 24 then why is this app not certified for 24?

**Comment by dafi87** [comment]
This is currently holding me back from updating to NC24. Would be nice to get a comment from the developer.
Thanks!

**Comment by emombiela** [comment]
Hello! I want to update NC from version 24.0.2 to 24.0.3.
The app keeps showing up as not supported.
The app still works for NC24. Would it be possible to update the app registration so that it appears as a supported app?

Thanks!

**Comment by mapausch** [comment]
@icewind1991 are there any known issues in this app together with NC 24?

Following this issue it seems like the current version of this app also works with NC 24, but is not yet "certified" for NC 24.
So it currently only can be activated as "untested app", which "block" some users from upgrading to NC 24.

Thanks for your work.

**Comment by jet438** [comment]
Ha

**Comment by juliushaertl** [comment]
Just released a new version for 24 and 25
