### ISSUE TITLE
feature request:  add files_texteditor to nextcloud app store

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/files_texteditor#97]
The Official PDF Viewer [is on the App Store](https://apps.nextcloud.com/apps/files_pdfviewer). It would be much easier if `files_texteditor` were also on the App Store. This also simplifies the installation.

```
php occ app:install files_texteditor
```

**Comment by compumatter** [comment]
Totally agree with this. Existing support post on this exists: https://help.nextcloud.com/t/shared-text-files-download-not-opening-in-nextcloud-editor/32249/4

**Comment by mritzmann** [comment]
Problem is that files_texteditor is not available in the git version of Nextcloud. A store variant would therefore be desirable.

**Comment by mritzmann** [comment]
Is now on the App Store: https://apps.nextcloud.com/apps/files_texteditor
